// Copyright (c) the go-ruby-irb/irb authors
//
// SPDX-License-Identifier: BSD-3-Clause

package irb

// continuationCorpus is the shared set of Ruby snippets used by both the
// deterministic golden tests (TestCheckCodeGolden) and the MRI oracle
// (TestOracleContinuation). Each snippet exercises a distinct continuation /
// indent / ltype decision in RubyLex.
var continuationCorpus = []string{
	"1 + 1",
	"def foo",
	"def foo; end",
	"[1,2,",
	"[1,2]",
	"x = (",
	"x = (1)",
	"\"abc",
	"\"abc\"",
	"a +",
	"a.",
	"a.b",
	"if true\n  1\nend",
	"if true\n  1",
	"1 +\\",
	"{a: 1",
	"{a: 1}",
	"begin\n  x",
	"begin\n  x\nend",
	"case x\nwhen 1",
	"case x\nwhen 1\n  2\nend",
	"<<~HEREDOC",
	"<<~HEREDOC\n  hi\nHEREDOC",
	"[1,2].map do |x|",
	"[1,2].map do |x|\n  x\nend",
	"%w[a b",
	"%w[a b]",
	"x ? y :",
	"x ? y : z",
	"end",
	"1..",
	"1...",
	"1..2",
	"foo bar",
	"class C\n  def m\n  end",
	"class C\n  def m\n  end\nend",
	"/regex",
	"/regex/",
	":sym",
	"@ivar = 1",
	"$g = 1",
	"@@c = 1",
	"CONST = 1",
	"module M",
	"module M\nend",
	"while true",
	"while true\nend",
	"until x\n  y",
	"for i in 1..3",
	"for i in 1..3\n  i\nend",
	"foo(",
	"foo()",
	"puts 'hi'",
	"x = [\n1,\n2,\n]",
	"1 +\n2",
	"a &&",
	"a ||",
	"a, b =",
	"a, b = 1, 2",
	"def self.foo",
	"def self.foo\nend",
	"->(x) {",
	"->(x) { x }",
	"%i(a b",
	"%i(a b)",
	"p(:a)",
	"if x then y end",
	"unless x then y end",
	"foo if bar",
	"x = 1 while false",
	"`ls",
	"`ls`",
	"=begin\nfoo\n=end",
	"\"a#{b",
	"\"a#{b}c\"",
	"raise\nbar",
	"alias foo bar",
	"hash = { 'a' => 1 }",
	"def foo(a, b)",
	"def foo(a, b)\nend",
	"def foo = 1",
	"def foo a, b",
	"def foo a, b\nend",
	"[",
	"]",
	")",
	"}",
	"x = {",
	"x = {\n}",
	"a\n.b",
	"a\n.b\n.c",
	"begin\nrescue\nend",
	"begin\nensure\nend",
	"if a\nelsif b\nend",
	"if a\nelse\nend",
	"loop do",
	"loop do\nend",
	"3.times { |i|",
	"3.times { |i| i }",
	"case x\nin [1, 2]",
	"case x\nin [1, 2]\n  :ok\nend",
	"undef foo",
	"x = <<-END\n  body\n  END",
	"x = <<'END'\nbody\nEND",
	"\"#{1 + ",
	"\"#{1 + 2}\"",
	"a = b = c =",
	"a = b = c = 1",
	"!foo",
	"not foo",
	"return",
	"return 1",
	"yield",
	"super",
	"defined?(x)",
	"obj&.foo",
	"obj&.foo.bar",
	"1 if",
	"[*a]",
	"{**h}",
	"foo(*args)",
	"x.y = ",
	"x.y = 1",
	"class << self",
	"class << self\nend",
	"module M; class C; end; end",
	"BEGIN {",
	"END {",
	"p 1; p 2",
	"a ||= 1",
	"a += ",
	"a += 1",
	"\t  indented",
	"# just a comment",
	"x = 1 # trailing",
	"\"line1\nline2\"",
	"'single\nquote'",
	"heredoc = <<~SQL\n  SELECT *\nSQL",
}

// colorCorpus is the shared set of snippets for the colorize tests
// (TestColorizeGolden and TestOracleColorize).
var colorCorpus = []string{
	"1 + 2", "\"str\"", ":sym", "@ivar", "$gvar", "@@cv", "CONST", "nil",
	"true", "false", "self", "# comment", "/regex/", "1.5", "1r", "1i",
	"foo.bar", "x = 1", "{a: 1}", "%w[a b]", "`cmd`", "def foo; end",
	"[1, 2, 3]", "puts 'hello'", "a ? b : c", "1..10", "x ||= 5",
	"\"a#{b}c\"", "class C; end", "->(x){ x }", "__FILE__", "0xff",
	":\"quoted sym\"", "%i(a b c)", "$0", "$1", "ENV", "@@class_var",
	"[1, :two, \"three\"]", "1_000_000", "3.14e10", "?a",
	"# multi\n# line", "a = b\nc = d", "def m(x)\n  x\nend",
	"module Foo\nend", "x = /pat/i", "h = {key: :value}",
}

// indentCorpus drives the auto-indent oracle (TestOracleAutoIndent) and golden
// (TestAutoIndentGolden). Each case is [source, line index, is-newline].
var indentCorpus = []struct {
	Code      string
	LineIndex int
	IsNewline bool
}{
	{"if true\n", 1, true},
	{"if true\n  x\n", 2, true},
	{"def foo\n", 1, true},
	{"class C\n  def m\n", 2, true},
	{"[1,\n", 1, true},
	{"x = {\n", 1, true},
	{"  if a\n", 1, true},
	{"begin\n  x\nrescue\n", 3, true},
	{"if a\n  b\nend\n", 3, true},
	{"while x\n", 1, true},
	{"case y\nwhen 1\n", 2, true},
	{"[1, 2].each do |n|\n", 1, true},
	{"module M\n  class C\n    def f\n", 3, true},
	{"x = [\n  1,\n", 2, true},
	{"foo(\n", 1, true},
	{"  nested\n    deeper\n", 2, true},
	// heredoc bodies and close lines (squiggly / dashed / plain)
	{"x = <<~SQL\n", 1, true},
	{"x = <<~SQL\n  SELECT 1\n", 2, true},
	{"x = <<~SQL\n  SELECT 1\nSQL\n", 3, true},
	{"  y = <<~SQL\n", 1, true},
	{"  y = <<~SQL\n    body\n", 2, true},
	{"x = <<-END\n", 1, true},
	{"x = <<-END\n  body\n  END\n", 3, true},
	{"x = <<END\n", 1, true},
	{"x = <<END\nbody\n", 2, true},
	// free-indent string literal continuation
	{"x = \"first\n", 1, true},
	{"x = \"first\n  second\n", 2, false},
	{"x = \"first\n", 1, false},
	// =begin / =end embdoc
	{"=begin\n", 1, true},
	{"=begin\ndoc\n", 2, true},
	{"=begin\ndoc\n=end\n", 3, true},
	// re-indent the current (non-newline) line
	{"if a\n  b", 1, false},
	// heredoc close lines (squiggly / dashed / plain) and nested-heredoc base
	{"  x = <<~SQL\n    body\n  SQL\n", 2, true},
	{"  x = <<-END\n    body\n  END\n", 2, true},
	{"x = <<END\nbody\nEND\n", 2, true},
	{"  if a\n    x = <<~SQL\n      body\n", 3, true},
	{"if a\n  b = <<~T\n    c\n  T\n", 3, true},
	// multiple heredocs queued on one line — the second's base indent recurses
	// through indentDifference past the first heredoc open.
	{"x = [<<~A, <<~B]\n  aa\n", 2, true},
	{"foo(<<~A, <<~B)\n  a\n  A\n  bb\n", 4, true},
	// an inner block opener pasted under-indented relative to its nesting makes
	// indentDifference negative, which is clamped to a zero base indent.
	{"def m\nif x\n  y\n", 2, true},
	{"class C\nif a\nb\n", 2, true},
}
